### ISSUE TITLE
TypeError: Data location must be "memory" for return pa rameter in function, but none was given.

### ISSUE THREAD

**Issue by salmeghlef** [gladiusio/gladius-contracts#49]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Node 7.6.0 on Ganache GUI):
* Operating System and version: 
* Link to your project:

**Comment by alex-godwin** [comment]
Fixed with the newest changes in master. Try using the CLI we added to make deployment easier as well.
