### ISSUE TITLE
Payment System

### ISSUE THREAD

**Issue by Celo44** [gladiusio/gladius-contracts#9]
Implement and refine new payment system to keep track of all account balances for marketplace and pools.

**Comment by nfeld9807** [comment]
See Team Drive `Balance Sheet Examples` for examples

**Comment by nfeld9807** [comment]
`payable + total == available + workable + withdrawable + completed + ( - paid )`

**Comment by nfeld9807** [comment]
Moving to Sprint 4 to integrate with new Node and Client Contracts
